In [8]:
import numpy as np

x=np.zeros((4,4),dtype=int) #initialize array

print(x)

y=np.ones((4,4),dtype=float)
print(y)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
data=np.array([('Senna',2,21.0),('Manish',7,29.0)],
              dtype=[('name',(np.str_,10)),('age',np.int32),('weight',np.float64)])

print(data)

sn=np.sort(data,order='name')
print('SOrting according to name :',sn)

sa=np.sort(data,order='age')
print('SOrting according to age :',sa)

[('Senna', 2, 21.) ('Manish', 7, 29.)]
SOrting according to name : [('Manish', 7, 29.) ('Senna', 2, 21.)]
SOrting according to age : [('Senna', 2, 21.) ('Manish', 7, 29.)]


In [3]:
dt=np.ones(4,dtype={'names':('name','age','weight'),
                     'formats':('U10','i4','f8')})
print(data.dtype)

dt['name']='Thomas'
dt['age']='33'
dt['weight']='61'
print(dt)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('Thomas', 33, 61.) ('Thomas', 33, 61.) ('Thomas', 33, 61.)
 ('Thomas', 33, 61.)]


In [5]:
row=5
col=6
table=np.ones(5,dtype={'names':('roll_no','name','class','section','course','marks'),
                               'formats':('i4','U30','U2','U1','U50','f8')})
roll=[1,2,3,4,5]
name=['Ben','Bob','Charlie','Jake','Troy']
clas=[12,12,11,11,11]
sec=['A','A','C','B','C']
crse=['Science','Commerce','Commerce','Science','Science']
mks=[89.5,91.0,86.7,96.6,90.4]

In [6]:
table['roll_no']=roll
table['name']=name
table['class']=clas
table['section']=sec
table['course']=crse
table['marks']=mks
print(table)

[(1, 'Ben', '12', 'A', 'Science', 89.5)
 (2, 'Bob', '12', 'A', 'Commerce', 91. )
 (3, 'Charlie', '11', 'C', 'Commerce', 86.7)
 (4, 'Jake', '11', 'B', 'Science', 96.6)
 (5, 'Troy', '11', 'C', 'Science', 90.4)]


In [16]:
a=np.array([1,3,4])
b=np.array([2,2,7])
c=a<b

In [17]:
print(c)

[ True False  True]


In [18]:
print(c.all()) #were all true?

False


In [19]:
print(c.any()) #atleast one is true

True


In [23]:
print(c.sum())

2


In [24]:
c=a>2
print(a[c]) #masking
print(a[~c])
a[~c]=0
print(a)

[3 4]
[0]
[0 3 4]


In [21]:
n1=np.random.randint(0,20,30)
print(n1)
n2=np.array([n1[2],n1[5],n1[7]])
idx=[2,3,4]
print(n1[idx])

[ 6  6 12  1  9 15 14  4 17  7 15  0 16 10 11  2 13  8  2  9 19 10 14 11
 16 14 11  1 17  9]
[12  1  9]


In [22]:
b=np.arange(16).reshape(4,4)
print(b)
row=np.array([0,2])
col=np.array([0,3])
print(b[row,col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0 11]


In [25]:
arr=np.array([[66,88],[94,47]])

In [26]:
np.sum(arr)

295

In [28]:
np.average(arr)

73.75

In [29]:
np.max(arr)

94

In [30]:
np.min(arr)

47

In [31]:
np.product(arr)

25659744